export default class Naming {

  static NAME_STR_PIECE_MARK = 'STR_PIECE_MARK';
  static NAME_STR_CONSTRUCTION = 'STR_CONSTRUCTION';
  static NAME_STR_QC= 'STR_QC';
  static NAME_STR_LAM_CHECK_REQUEST = 'STR_LAM_CHECK_REQUEST';
  static NAME_STR_LAM_CHECK_TODO = 'STR_LAM_CHECK_TODO';
  static NAME_STR_DIM_CHECK = 'STR_DIM_CHECK';

};
